package view;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Book;
import utils.BookDAO;
import utils.BookManagement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class Edit_Book extends javax.swing.JFrame {

    /**
     * Creates new form newBook
     */
    public Edit_Book(String title) {
        initComponents();
        this.pack();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.title_TF.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBook_label = new javax.swing.JLabel();
        title_label = new javax.swing.JLabel();
        type_label = new javax.swing.JLabel();
        yOR_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        title_TF = new javax.swing.JTextField();
        type_TF = new javax.swing.JTextField();
        yOR_TF = new javax.swing.JTextField();
        price_TF = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBook_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addBook_label.setForeground(new java.awt.Color(0, 0, 0));
        addBook_label.setText("EDIT BOOK INFORMATION");
        getContentPane().add(addBook_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 240, -1));

        title_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        title_label.setForeground(new java.awt.Color(0, 0, 0));
        title_label.setText("Title");
        getContentPane().add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 34, -1));

        type_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        type_label.setForeground(new java.awt.Color(0, 0, 0));
        type_label.setText("Type");
        getContentPane().add(type_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 40, -1));

        yOR_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        yOR_label.setForeground(new java.awt.Color(0, 0, 0));
        yOR_label.setText("Year Of Release");
        getContentPane().add(yOR_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        price_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        price_label.setForeground(new java.awt.Color(0, 0, 0));
        price_label.setText("Price");
        getContentPane().add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 50, -1));

        title_TF.setBackground(new java.awt.Color(255, 255, 255));
        title_TF.setCaretColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(title_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, -1));

        type_TF.setBackground(new java.awt.Color(255, 255, 255));
        type_TF.setForeground(new java.awt.Color(0, 0, 0));
        type_TF.setCaretColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(type_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, -1));

        yOR_TF.setBackground(new java.awt.Color(255, 255, 255));
        yOR_TF.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(yOR_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, -1));

        price_TF.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(price_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, -1));

        update_button.setBackground(new java.awt.Color(0, 102, 255));
        update_button.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        update_button.setText("UPDATE");
        update_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 399, 70, 30));

        close_button.setBackground(new java.awt.Color(255, 255, 255));
        close_button.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        close_button.setForeground(new java.awt.Color(0, 0, 0));
        close_button.setText("CLOSE");
        close_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 60, 30));

        background_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/register.png"))); // NOI18N
        getContentPane().add(background_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        String title = title_TF.getText();
        String type = type_TF.getText();
        int yOR = Integer.parseInt(yOR_TF.getText());
        int price = Integer.parseInt(price_TF.getText());
        Book updateBook = new Book(title, type, yOR, price);
        BookManagement.editBook_info(title, updateBook);
        JOptionPane.showMessageDialog(null, "Editting user successfully", "Success", JOptionPane.PLAIN_MESSAGE);
        BookDAO.saveBookListBy_Char(BookManagement.getListBook());
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBook_label;
    private javax.swing.JLabel background_label;
    private javax.swing.JButton close_button;
    private javax.swing.JTextField price_TF;
    private javax.swing.JLabel price_label;
    private javax.swing.JTextField title_TF;
    private javax.swing.JLabel title_label;
    private javax.swing.JTextField type_TF;
    private javax.swing.JLabel type_label;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField yOR_TF;
    private javax.swing.JLabel yOR_label;
    // End of variables declaration//GEN-END:variables
}
