package view;


import javax.swing.JOptionPane;
import model.User;
import utils.UserDAO;
import utils.UserManagement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class Edit_User extends javax.swing.JFrame {

    UserDAO userDAO = new UserDAO();

    /**
     * Creates new form NewUser
     */
    public Edit_User(String id) {
        initComponents();
        this.setTitle("MUJI LIBRARY EDIT FORM");
        this.pack();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.userID_TF.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationTitle_label = new javax.swing.JLabel();
        userID_label = new javax.swing.JLabel();
        userID_TF = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_F = new javax.swing.JPasswordField();
        age_label = new javax.swing.JLabel();
        age_TF = new javax.swing.JTextField();
        fullname_label = new javax.swing.JLabel();
        fullname_TF = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationTitle_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registrationTitle_label.setForeground(new java.awt.Color(0, 0, 0));
        registrationTitle_label.setText("EDIT USER INFORMATION");
        getContentPane().add(registrationTitle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 290, -1));

        userID_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        userID_label.setForeground(new java.awt.Color(0, 0, 0));
        userID_label.setText("User ID");
        getContentPane().add(userID_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 65, -1));

        userID_TF.setBackground(new java.awt.Color(0, 0, 0));
        userID_TF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(userID_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, -1));

        password_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        password_label.setForeground(new java.awt.Color(0, 0, 0));
        password_label.setText("Password");
        getContentPane().add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 55, -1));

        password_F.setBackground(new java.awt.Color(0, 0, 0));
        password_F.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 210, -1));

        age_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        age_label.setForeground(new java.awt.Color(51, 51, 51));
        age_label.setText("Age");
        getContentPane().add(age_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 34, -1));

        age_TF.setBackground(new java.awt.Color(0, 0, 0));
        age_TF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 56, -1));

        fullname_label.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        fullname_label.setForeground(new java.awt.Color(0, 0, 0));
        fullname_label.setText("Fullname");
        getContentPane().add(fullname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 55, -1));

        fullname_TF.setBackground(new java.awt.Color(0, 0, 0));
        fullname_TF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(fullname_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 210, -1));

        update_button.setBackground(new java.awt.Color(0, 102, 255));
        update_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update_button.setForeground(new java.awt.Color(255, 255, 255));
        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 90, -1));

        close_button.setBackground(new java.awt.Color(255, 255, 255));
        close_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        close_button.setForeground(new java.awt.Color(0, 0, 0));
        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/register.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        String ID = userID_TF.getText();
        String password = new String(password_F.getPassword());
        String fullname = fullname_TF.getText();
        String age = age_TF.getText();
        User user = new User(ID, password, fullname, age);
        UserManagement.editUser_info(ID, user);
        JOptionPane.showMessageDialog(null, "Editting user successfully", "Success", JOptionPane.PLAIN_MESSAGE);
        userDAO.saveUserListBy_Char(UserManagement.getListUser());
    }//GEN-LAST:event_update_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_TF;
    private javax.swing.JLabel age_label;
    private javax.swing.JLabel background;
    private javax.swing.JButton close_button;
    private javax.swing.JTextField fullname_TF;
    private javax.swing.JLabel fullname_label;
    private javax.swing.JPasswordField password_F;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel registrationTitle_label;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField userID_TF;
    private javax.swing.JLabel userID_label;
    // End of variables declaration//GEN-END:variables
}
