package view;


import view.Login;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
        this.setTitle("MUJI MANAGEMENT HOMEPAGE");
        this.setLocationRelativeTo(null);
        this.pack();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.newUser_button.setContentAreaFilled(false);
        this.newBook_button.setContentAreaFilled(false);
        this.statistics_button.setContentAreaFilled(false);
        this.logOut_button.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUser_button = new javax.swing.JButton();
        newBook_button = new javax.swing.JButton();
        statistics_button = new javax.swing.JButton();
        logOut_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUser_button.setBackground(new java.awt.Color(255, 255, 255));
        newUser_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        newUser_button.setForeground(new java.awt.Color(255, 51, 153));
        newUser_button.setText("New User");
        newUser_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUser_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(newUser_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        newBook_button.setBackground(new java.awt.Color(255, 255, 255));
        newBook_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        newBook_button.setForeground(new java.awt.Color(255, 51, 153));
        newBook_button.setText("New Book");
        newBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBook_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(newBook_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        statistics_button.setBackground(new java.awt.Color(255, 255, 255));
        statistics_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        statistics_button.setForeground(new java.awt.Color(255, 51, 153));
        statistics_button.setText("Statistics");
        statistics_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistics_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(statistics_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        logOut_button.setBackground(new java.awt.Color(255, 255, 255));
        logOut_button.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        logOut_button.setForeground(new java.awt.Color(255, 51, 153));
        logOut_button.setText("Log Out");
        logOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(logOut_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BG.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newUser_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUser_buttonActionPerformed
        // TODO add your handling code here:
        new NewUser().setVisible(true);

    }//GEN-LAST:event_newUser_buttonActionPerformed

    private void logOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logOut_buttonActionPerformed

    private void statistics_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistics_buttonActionPerformed
        // TODO add your handling code here:
        new Statistics().setVisible(true);

    }//GEN-LAST:event_statistics_buttonActionPerformed

    private void newBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBook_buttonActionPerformed
        // TODO add your handling code here:
        new NewBook().setVisible(true);
    }//GEN-LAST:event_newBook_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton logOut_button;
    private javax.swing.JButton newBook_button;
    private javax.swing.JButton newUser_button;
    private javax.swing.JButton statistics_button;
    // End of variables declaration//GEN-END:variables
}
