package view;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("MUJI LIBRARY MANAGEMENT LOGIN");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userID_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        userID_TF = new javax.swing.JTextField();
        password_F = new javax.swing.JPasswordField();
        login_Button = new javax.swing.JButton();
        close_Button = new javax.swing.JButton();
        loginTitle_label = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userID_label.setBackground(new java.awt.Color(0, 0, 0));
        userID_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userID_label.setForeground(new java.awt.Color(0, 0, 0));
        userID_label.setText("User ID");
        getContentPane().add(userID_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 80, -1));

        password_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        password_label.setForeground(new java.awt.Color(0, 0, 0));
        password_label.setText("Password");
        getContentPane().add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, -1));

        userID_TF.setBackground(new java.awt.Color(255, 255, 255));
        userID_TF.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userID_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, 30));

        password_F.setBackground(new java.awt.Color(255, 255, 255));
        password_F.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(password_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, 30));

        login_Button.setBackground(new java.awt.Color(31, 94, 221));
        login_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login_Button.setForeground(new java.awt.Color(255, 255, 255));
        login_Button.setText("Login");
        login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 80, 30));

        close_Button.setBackground(new java.awt.Color(255, 255, 255));
        close_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close_Button.setForeground(new java.awt.Color(0, 0, 0));
        close_Button.setText("Close");
        close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(close_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, 30));

        loginTitle_label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        loginTitle_label.setForeground(new java.awt.Color(0, 0, 0));
        loginTitle_label.setText("LOGIN");
        getContentPane().add(loginTitle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/register.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ButtonActionPerformed
        // TODO add your handling code here:
        String password = new String(password_F.getPassword());
        if (userID_TF.getText().equals("admin") && (password.equals("admin"))) {
            this.setVisible(false);
            new Homepage().setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Incorrect User !", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_login_ButtonActionPerformed

    private void close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_close_ButtonActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton close_Button;
    private javax.swing.JLabel loginTitle_label;
    private javax.swing.JButton login_Button;
    private javax.swing.JPasswordField password_F;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField userID_TF;
    private javax.swing.JLabel userID_label;
    // End of variables declaration//GEN-END:variables
}
