package view;


import view.Login;
import java.awt.Color;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Asus
 */
public class SplashCreen extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form SplashCreen
     */
    public SplashCreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Loading Time");
        Thread t = new Thread(this);
        t.start();

    }

    @Override
    public void run() {
        for (int i = 0; i <= 100; i++) {
            try {
                Thread.sleep(50);
            } catch (Exception e) {
            }
            this.loadingNumber.setText(i + "%");
            this.progressBar.setValue(i);
            if (i == 100) {
                Login login = new Login();
                this.dispose();
                login.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        loadingNumber = new javax.swing.JLabel();
        bgSplash_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setBackground(new java.awt.Color(255, 0, 0));
        progressBar.setBorderPainted(false);
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        progressBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 590, -1));

        loadingNumber.setBackground(new java.awt.Color(255, 255, 255));
        loadingNumber.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        loadingNumber.setForeground(new java.awt.Color(0, 0, 0));
        loadingNumber.setText("0%");
        loadingNumber.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(loadingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 120, -1));

        bgSplash_label.setForeground(new java.awt.Color(255, 255, 255));
        bgSplash_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/loading.png"))); // NOI18N
        getContentPane().add(bgSplash_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashCreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashCreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashCreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashCreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashCreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgSplash_label;
    public javax.swing.JLabel loadingNumber;
    public javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

}
